/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./components/hymn/AudioPlayer.vue')['default']
    Background: typeof import('./components/common/Background.vue')['default']
    Breadcrumbs: typeof import('./components/home/Breadcrumbs.vue')['default']
    Chevron: typeof import('./components/icons/Chevron.vue')['default']
    Close: typeof import('./components/icons/Close.vue')['default']
    EnterKey: typeof import('./components/icons/EnterKey.vue')['default']
    Filter: typeof import('./components/icons/Filter.vue')['default']
    FullSearch: typeof import('./components/icons/FullSearch.vue')['default']
    Grid: typeof import('./components/icons/Grid.vue')['default']
    HymnItem: typeof import('./components/home/HymnItem.vue')['default']
    List: typeof import('./components/icons/List.vue')['default']
    ListView: typeof import('./components/home/ListView.vue')['default']
    Moon: typeof import('./components/icons/Moon.vue')['default']
    NarrowArrow: typeof import('./components/icons/NarrowArrow.vue')['default']
    Navbar: typeof import('./components/hymn/Navbar.vue')['default']
    Pagination: typeof import('./components/common/Pagination.vue')['default']
    Pause: typeof import('./components/icons/Pause.vue')['default']
    Play: typeof import('./components/icons/Play.vue')['default']
    Present: typeof import('./components/icons/Present.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/icons/Search.vue')['default']
    SearchButton: typeof import('./components/search/SearchButton.vue')['default']
    SearchCommand: typeof import('./components/search/SearchCommand.vue')['default']
    SearchInput: typeof import('./components/search/SearchInput.vue')['default']
    Sort: typeof import('./components/icons/Sort.vue')['default']
    Stop: typeof import('./components/icons/Stop.vue')['default']
    Sun: typeof import('./components/icons/Sun.vue')['default']
    XDropdown: typeof import('./components/common/XDropdown.vue')['default']
  }
}
