/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./components/home/Breadcrumbs.vue')['default']
    Chevron: typeof import('./components/icons/Chevron.vue')['default']
    Filter: typeof import('./components/icons/Filter.vue')['default']
    Grid: typeof import('./components/icons/Grid.vue')['default']
    HymnItem: typeof import('./components/home/HymnItem.vue')['default']
    List: typeof import('./components/icons/List.vue')['default']
    ListView: typeof import('./components/home/ListView.vue')['default']
    Moon: typeof import('./components/icons/Moon.vue')['default']
    Pagination: typeof import('./components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sort: typeof import('./components/icons/Sort.vue')['default']
    Sun: typeof import('./components/icons/Sun.vue')['default']
    XDropdown: typeof import('./components/common/XDropdown.vue')['default']
  }
}
